Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from vampires_dpp.image_registration import satellite_spot_offsets
from vampires_dpp.satellite_spots import lamd_to_pixel

# radius of satellite spots
radius = lamd_to_pixel(31.6, abaur20220224_hdr["U_FILTER"])

kwargs = {
    "center": (130, 130),
    "window": 30,
    "radius": radius,
    "refidx": frame_idx_coro,
}


offsets_coro_com = satellite_spot_offsets(abaur20220224_cube, method="com", **kwargs)
offsets_coro_peak = satellite_spot_offsets(abaur20220224_cube, method="peak", **kwargs)
offsets_coro_dft = satellite_spot_offsets(
    abaur20220224_cube, method="dft", refmethod="com", upsample_factor=1, **kwargs
)
offsets_coro_dft_10 = satellite_spot_offsets(
    abaur20220224_cube, method="dft", refmethod="com", upsample_factor=10, **kwargs
)
offsets_coro_moffat = satellite_spot_offsets(
    abaur20220224_cube, method="moffat", **kwargs
)
offsets_coro_gaussian = satellite_spot_offsets(
    abaur20220224_cube, method="gaussian", **kwargs
)
offsets_coro_airydisk = satellite_spot_offsets(
    abaur20220224_cube, method="airydisk", **kwargs
)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[11], line 2[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mvampires_dpp[39;00m[38;5;21;01m.[39;00m[38;5;21;01mimage_registration[39;00m [38;5;28;01mimport[39;00m satellite_spot_offsets
[0;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mvampires_dpp[39;00m[38;5;21;01m.[39;00m[38;5;21;01msatellite_spots[39;00m [38;5;28;01mimport[39;00m lamd_to_pixel
[1;32m      4[0m [38;5;66;03m# radius of satellite spots[39;00m
[1;32m      5[0m radius [38;5;241m=[39m lamd_to_pixel([38;5;241m31.6[39m, abaur20220224_hdr[[38;5;124m"[39m[38;5;124mU_FILTER[39m[38;5;124m"[39m])

[0;31mModuleNotFoundError[0m: No module named 'vampires_dpp.satellite_spots'
ModuleNotFoundError: No module named 'vampires_dpp.satellite_spots'

